apiVersion: v1
kind: Secret
metadata:
  name: alert-webhook-secret
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  BALE_TOKEN: {{ .Values.env.BALE_TOKEN | b64enc | quote }}
  BALE_CHAT_ID: {{ .Values.env.BALE_CHAT_ID | b64enc | quote }}
